{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "osync.serviceAccountName" . }}
  labels:
    {{- include "osync.labels" . | nindent 4 }}
{{- end }}
