name: Release on main push

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine repository
        id: release-version
        run: |
          echo "repository=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ steps.release-version.outputs.repository }}
          tags: |
            type=semver,pattern={{version}},value=${{ github.ref_name }}
          flavor: |
            latest=auto

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        id: build-push
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.release-version.outputs.tag }}
          name: Release ${{ steps.release-version.outputs.tag }}
          body: |
            ## 📦 Release Summary

            This release was automatically generated from commit [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}).

            ## 🐳 How to use this image

            ```sh
            docker pull ghcr.io/${{ github.repository }}:${{ steps.release-version.outputs.tag }}
            docker run --rm ghcr.io/${{ github.repository }}:${{ steps.release-version.outputs.tag }}
            ```

            Or always use the latest version:
            ```sh
            docker pull ghcr.io/${{ github.repository }}:latest
            ```

            ---
            This release was automatically generated by the GitHub Actions workflow.