name: Release on main push

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Determine repository
        id: release-version
        run: |
          echo "repository=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ steps.release-version.outputs.repository }}
          tags: |
            type=semver,pattern={{version}},value=${{ github.ref_name }}
          flavor: |
            latest=auto

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        id: build-push
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update Helm chart version
        run: |
          sed -i "s/^version: .*/version: ${{ github.ref_name }}/" chart/Chart.yaml
      
      - name: Package Helm chart
        run: |
          helm package chart --destination target

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Update Helm repo index
        run: |
          cp target/*.tgz gh-pages/
          cd gh-pages
          helm repo index . --url https://nicolasstr.github.io/osync-container

      - name: Commit and push Helm chart to gh-pages
        run: |
          cd gh-pages
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Update Helm chart for ${{ github.ref_name }}" || echo "No changes to commit"
          git push

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## 📦 Release Summary

            This release was automatically generated from commit [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}).

            # 🚀 Deploy

            ## 🐳 Using Docker

            You can pull the Docker image for this release using the following command:

            ```sh
            docker pull ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            docker run --rm ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            ```

            Or always use the latest version:
            ```sh
            docker pull ghcr.io/${{ github.repository }}:latest
            ```

            ## ⎈ Using Helm

            You can deploy this release using Helm with the following command:

            ```sh
            helm repo add osync https://nicolasstr.github.io/osync-container
            helm repo update
            # Create a values.yaml file with your configuration
            vim values.yaml
            # Then install the chart with your values
            helm install osync osync/osync --version ${{ github.ref_name }} -f values.yaml
            ```

            ---
            This release was automatically generated by the GitHub Actions workflow.